# _config.yml

# Site Settings
title: Some Guide and Resources
baseurl: "" # The subpath of your site, e.g. /blog.
url: "https://itshaihong.github.io/StudentGuide" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Optional: Set a permalink style
permalink: /:title/
