# _config.yml

# Site Settings
title: reComputer J30/40 Setup Guide
description: Getting started and configuring the Seeed Studio reComputer J30/40 for Edge AI deployment.
baseurl: "" # The subpath of your site, e.g. /blog.
url: "https://itshaihong.github.io/StudentGuide" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Optional: Set a permalink style
permalink: /:title/
